<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <!-- Avalonia Controls package -->
    <PackageReference Include="Avalonia" Version="11.1.3" />
    
    <!-- WebView2 for Windows -->
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2420.47" />
  </ItemGroup>

</Project>